### ISSUE TITLE
Fix Timeseries Labels for 2 Layers

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#214]
For the following two layers, there are strange labels that appear in the timeseries slider, e.g.:
![image.png](https://images.zenhubusercontent.com/5b51ec168c1a7628d9218a4b/4b379458-c692-41e3-9385-d9f693d10f57)

RC - Adolescents (15-18 years) enrolled in non-formal/formal education
HC - children under five attended for healthcare

We should fix that

**Comment by cKellyDesign** [comment]
This is happening because the [report form](https://ona.io/unicef_bco/49200/315361) has changed by adding new time-periods which pre-date the original beginning of the timeseries. New time periods which adhere to the same `MM d` date format [they can simply be added to the layer spec with new unique keys](https://github.com/onaio/rohingya/blob/master/public/config/layers/Education-adolescents-15-to-18.json#L117-L130).

However, the very first new time period uses a different date format, which would require additional dev work to account for multiple types of date formats when aggregating data into time periods. This would be a light lift but would still be a lift for an upgrade to the existing basic functionality.

<img width="747" alt="screen shot 2018-09-13 at 12 41 19 pm" src="https://user-images.githubusercontent.com/4141527/45502863-25d9cf00-b753-11e8-98e0-4d2134dd311d.png">

**Comment by cKellyDesign** [comment]
A) Fixing this introduces labels longer than the slider component, so we'll have to adjust that.
B) [In the future] we should move data parsing configurations into the site config so they can be managed in one place (instead of every layer).
