### ISSUE TITLE
Define Plan for Auth in Gisida

### ISSUE THREAD

**Issue by royrutto-xx** [onaio/gisida#34]
Setup alternative authentication methods:
- [x] OAuth via Ona API, Superset Google Accounts, are viable for implementation
- [x] Write up Gisida Auth Requirements Doc
- [x] [Meet](https://docs.google.com/document/d/1D8rkr8W7OuyWCAIXMQ71JBCHdYgAWCU-dHHzEXP9bnk/edit#heading=h.6v6q45ngo1av) with Dickson + Canopy (+ Kaznet) folks to discuss a unified approach

**Comment by cKellyDesign** [comment]
Gisida authentication needs to do 2 things:
* Allow only registered parties to open and use the Gisida map and other features
* Secure data and layer configs to only be accessible to registered parties

**Game Plan**
To start, we can utilize ONA user management for authentication and token generation and we can use ONA uploads to store static CSV files which will then be locked down under the ONA user management.

**Comment by cKellyDesign** [comment]
Documentation on ONA Authentication API - https://api.ona.io/static/docs/authentication.html

**Comment by ukanga** [comment]
I will suggest using Oauth2, it is described in that document but I want to insist on the Oauth2 usage rather than the authorization token approach.

With regards to the approach, I think I do understand how with regards to dataset access how that will work. I am wondering how that will change how the user engages with a gisida dashboard. A better understanding of the different users interacting with gisida and what that means with access to the data would help me weigh in on the approach.

**Comment by cKellyDesign** [comment]
@ukanga Great, yeah seems like Oauth2 is a good route. Gisida typically represents data as map layers rather than explicitly revealing data sources, so I think the impact to the dashboard front-end experience will be pretty limited. We'll only have to update the login component and we could add a simple indication in the menu component as to which layers are using non-public data. 

The datasets in question are largely static CSV files so if we move that to ONA uploads then we can access those documents through the API. This will require setting up ONA accounts for new/existing Gisida clients who don't have them already and will effect the way the data/analysis team updates data. Changing the file locations should also be seamless in Gisida's ingest processes, we'll just have to make sure to update our error handling for cases of access denied or missing resources. By default any access-denied data / failed layers won't show in the menu but we could change this and show them as greyed out in those cases.

**Comment by cKellyDesign** [comment]
@ukanga @KipSigei - I'm struggling to follow the Oauth2 documentation and understand how exactly to implement this. From what I understand we should be using an implicet flow/grant-type but the docum

1) Since Gisida is a SPA, can we use the Implicit grant-type/flow? 
2) According to the documentation we can make calls directly to the API for authentication, but this requires the registered `client_id`, how can we do this with exposing this information?
3) What is the state parameter being passed in the example calls?
4) Are we able to use third-party libraries with the ONA Authentication Server?
(such as [jso](https://github.com/andreassolberg/jso) or [simple-oauth2](https://github.com/lelylan/simple-oauth2))

**Comment by cKellyDesign** [comment]
@KipSigei @pld @ukanga - These docs are the proposed Gisida Auth Protocols to make Gisida Oauth2 compliant while using supplemental authorization via an Auth.json config file (fetched by the ONA API). Feel free to review and comment!

**Gisida Authorization an Authentication Protocols**
[Gisida Auth Protocols.pdf](https://github.com/onaio/gisida/files/2291492/Gisida.Auth.Protocols.pdf)

**Gisida Auth User Journeys**
[Gisida Auth User Journeys.pdf](https://github.com/onaio/gisida/files/2291496/Gisida.Auth.User.Journeys.pdf)

**Comment by cKellyDesign** [comment]
### Steps to Implement
1. Update Gisida and Gisida-React
    a. Add simple React Router
    b. Add Auth Routes / Actions
    c. Update ONA Connector Module
2. Update Site Config json
3. Add new Auth Config json
4. Migrate Private Layers to ONA uploads
