### ISSUE TITLE
Heat map for Zimbabwe Idai recovery site 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#412]
On Zimbabwe recovery site, we would like to include a heat map that will be used to show concentration of sites as different colours based on floods damage and population density.

We would like to see it against population affected, with the latest population data against data from here https://data.humdata.org/dataset/highresolutionpopulationdensitymaps-zwe

The population should correlate to the damaged sites

This is tied to this issue:

**Comment by cKellyDesign** [comment]
From a Mapbox perspective this data source is a Raster layer type because the data is a high-resolution geotiff. If we can convert that to a tileset then we just need to add a new Layer Type (`raster`, not `heatmap`) to Gisida.

**Comment by cKellyDesign** [comment]
@akahure Please specify which `sites` layers need heatmap layers.

**Comment by cKellyDesign** [comment]
This should be a matter of adding a `heatmap` type layer, which handles data very similarly to `symbol` layers. In this case we do not have scalable/categorical data on the severity of damage at each site, so these layers should simply show site density.

Given that both heatmap and raster layers are expected to be used at the same time, let's make sure each have partial opacity so we can more easily see the areas of overlap between the two layers.

**Comment by cKellyDesign** [comment]
As discussed with @ciremusyoka: When we have categorical data for heatmap layers (e.g. `damage type` is something like `"collapsed"` or `"flooded"`) should be split into multiple heatmaps layers, one for each category.

The reason for this is because heatmaps are scalar visualizations (in both "density" and "color") which fluidly display a range of data (either by opacity or color) and do not visual categorical data very well. Instead we should should generate multiple heatmap layers with static colors and default `density` properties (which derive from point density).

### Implementation Strategy
Ideally, the functionality to generate the Mapbox stylespec for heatmap layers (regardless of Gisida 1x vs Gisida Views), should:

- [ ] 1. Accept parameters for categories and category colors

- [ ] 2. Generate styleSpecs for each category

- [ ] 3a. [Gisida 1x] Add the array of stylespecs to the `layerObj.styleSpec` and check for arrays in `gisida-react.Map` component

- [ ] 3b. [Gisida Views] Simply Add an array of heatmap `<Layer />` components in the Map render function
