### ISSUE TITLE
UNOPS IDAI summary popup review design 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#426]
In the implementation of the summary popup for Idai, the client has asked if we can design a better popup to represent the details we are collecting at ward level

The current design we are working with is shown below, with the categories currently 
![Screenshot from 2020-02-11 15-44-36](https://user-images.githubusercontent.com/43808025/74239465-f3862580-4ce8-11ea-9e0c-0ef1ec5f724d.png)

**Comment by cKellyDesign** [comment]
@akahure if we are to rebuild the tooltip and/or profile view we will need designs first.

**Comment by kahummer** [comment]
![Screenshot from 2020-02-11 18-36-48](https://user-images.githubusercontent.com/16018123/74252889-626e7900-4cff-11ea-998e-dec3367629ab.png)
@akahure @cKellyDesign still work in progress this may need some styling tweaks before we :rocket:

**Comment by cKellyDesign** [comment]
Awesome thanks @kahummer! Yup I think some visual tweaks and then it will be better than our default lists :)

- [ ] Remove `Name` and add the Ward name as the title of the popup
- [ ] Move `Population` above `Partners operating in the ward` (keep `:` b/c these aren't in a table)
- [ ] Add cell padding
- [ ] Set the table borders to be light grey instead of black
- [ ] Split table into two tables: `Composite Severity Needs Index` and `Damaged Infrastructure`
- [ ] Add an `<h3>` above each table 
- [ ] Remove `Composite Severity Needs Index` and `Damage/d` from the left column
- [x] Leave `Total Infrastructure Damage` as is
- [ ] Remove all `:` from the left column

**Comment by cKellyDesign** [comment]
### Updated tooltip
<img width="543" alt="Screen Shot 2020-02-11 at 10 19 34 AM" src="https://user-images.githubusercontent.com/4141527/74265810-0af8ea80-4cb8-11ea-95cc-e152bf78714b.png">

### Known Edge Cases
<img width="587" alt="Screen Shot 2020-02-11 at 10 13 07 AM" src="https://user-images.githubusercontent.com/4141527/74265491-81e1b380-4cb7-11ea-8aa5-6499b3089895.png">

**Comment by akahure** [comment]
@cKellyDesign @kahama94 it looks alot better if you ask me, thanks for the swift changes here. I have a meeting with the client shortly and will update the issue after

**Comment by akahure** [comment]
Can we move the Damages to go above the SNI index ? @kahama94

**Comment by kahummer** [comment]
@akahure sure

**Comment by cKellyDesign** [comment]
@kahummer can this ticket be closed?
