### ISSUE TITLE
On Spotlight the popup to show details does not show 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#428]
On https://spotlight.onalabs.org/

when a layer is turned on, the site does not show any popup data. 

### Scope
* All layers other than the `Demographics` section

**Comment by cKellyDesign** [comment]
@akahure Unfortunately I can't figure out which combination of Gisida/-React/-Private branches this client is using and can't get [`spotlight-zimbabwe`](https://github.com/onaio/spotlight-zimbabwe) to compile on my machine.

@kelvin-muchiri @kahummer - Which branches is this using?

**Comment by cKellyDesign** [comment]
### Deduction
It does look like the most recent bundle was either using an old version of Gisida or one of our Gisida versions that became divergent.

### Behind the Scenes
Judging by type the error being thrown when mousing over them map, this line is trying to call a `string` function on a `number`...

<img width="876" alt="Screen Shot 2020-02-14 at 10 39 05 AM" src="https://user-images.githubusercontent.com/4141527/74559549-94f3be00-4f19-11ea-8cff-8f86af41ca4c.png">

...and from the source of the error we can see how this could happen because the conditional is only checking that the value exists, not that it's a number...

<img width="420" alt="Screen Shot 2020-02-14 at 10 39 05 AM copy" src="https://user-images.githubusercontent.com/4141527/74559854-2b27e400-4f1a-11ea-8166-df8f841c76fd.png">

...yet if we [check the code](https://github.com/onaio/gisida/blob/master/src/map/addPopUp.js#L101-L102), this conditional looks different than what been compiled above and is actually checking that `rowItem[val.trim()]` is a number. In fact, if we [check the `blame` view](https://github.com/onaio/gisida/blame/master/src/map/addPopUp.js#L101) it looks like this issue was actually addressed a few months ago...

<img width="1255" alt="Screen Shot 2020-02-14 at 11 12 49 AM" src="https://user-images.githubusercontent.com/4141527/74560295-1f88ed00-4f1b-11ea-81e7-87bce510c293.png">

...though may have only been merged to staging/master branches only recently, explaining why this fix is not included in this deployment.

### The Fix
- [ ] Update the installed version of `gisida` / down-merge master/staging into the `gisida` branch this client is running on
- [ ] Test and Redeploy
- [ ] Update the client `package.json` to point specify which versions / branches are being used

**Comment by moshthepitt** [comment]
> Unfortunately I can't figure out which combination of Gisida/-React/-Private branches this client is using and can't get spotlight-zimbabwe to compile on my machine.

@kahummer @cKellyDesign  it seems to me that as a priority this information for this client and others should be documented somewhere.

**Comment by cKellyDesign** [comment]
Agreed, our client repos are always private so we can simply add a section to the readme outlining which branches we're using. This requires some extra overhead to upkeep but then we wouldn't run into this problem.

**Comment by moshthepitt** [comment]
> kahummer moved this from Parking Lot to Done in Gisida Projects (Client) 4 days ago

@kahummer do we need to close the issue while doing this?

**Comment by cKellyDesign** [comment]
> @kahummer do we need to close the issue while doing this?

Closing this ticket will shift column to Done, but not the other way around it seems.

Just "reopened" it anyways to track:
- [ ] add a `Branches` section to the client `readme.md` spotlight repo listing branches being used for gisida/-react/-private 

I will open a new ticket to do this task on our other active client repos.

**Comment by cKellyDesign** [comment]
> add a section to the readme outlining which branches we're using

Let's not do this. See https://github.com/onaio/gisida/issues/431 for more details.
