### ISSUE TITLE
Bug on UGATlas map explorer 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#449]
In UGATlas there is an issue when a user activates both the filler layer and the circle layer. 

The site drops one layer and does show both data sets on the map. To reproduce 
1. https://stage-ugatlas.onalabs.org/
2. Open map explorer
3. Pick refugee population 
4. Pick Health centers 

This is what shows 
![Screenshot - 2020-04-09T150451 270](https://user-images.githubusercontent.com/43808025/78893165-7c180c80-7a73-11ea-84b9-e872d16ea0bf.png)

**Comment by ciremusyoka** [comment]
@akahure  @cKellyDesign  Am looking in to this and the problem seems to be the filters. The filters displayed are for the recently selected layer and if they don't match with those of the previously selected layer no data returned for previously selected layer hence the behaviour. 
For the Above case `Refugee population` format is in form of year and month `2019 June`  while those of `Health Centers` have `2016/2017` format.

**Comment by samwata** [comment]
@ciremusyoka Is there a way we can filter data when it has different periods?
In this case, the two layers turned on have different periods

**Comment by ciremusyoka** [comment]
@samwata Curently there is no way.

**Comment by cKellyDesign** [comment]
> For the Above case Refugee population filter format is in form of year and month 2019 June while those of Health Centers have 2016/2017 format.

Yeah currently these two types of date are incompatible. 

@samwata @ciremusyoka - it could be possible to convert the `2016/17` format to `2016 June` if we multiply our rows so each district has 12 rows per year (with the same data). But that would multiply rows of all the data (making it 12x heavier), and I'm not sure that's what the client wants to see.

> 1. https://stage-ugatlas.onalabs.org/
> 2. Open map explorer
> 3. Pick refugee population
> 4. Pick Health centers

When selecting layers that don't have timeseries, we can't show the timeslider because it's specific to the layer (not global), and simply checks all active layers for matching time periods. So since the active layer (Health centers) doesn't have timeseries, the app doesn't know what period it should be checking the other layers against.

**Comment by akahure** [comment]
@cKellyDesign @ciremusyoka I think the only workaround, which would mean new feature request, would be to add time series for the different data sets selected and allow toggle between the datasets that are available to show the two. 

In my opinion, this is new and would def need considerable amount of effort, we can park it for now and revisit it later.

**Comment by cKellyDesign** [comment]
Closing this issue for now, it can be reopened if we decide to implement this as a new feature
